### ISSUE TITLE
Black formatted files fail to parse

### ISSUE THREAD

**Issue by lovetox** [pygobject/pygobject-stubs#168]
Currently parser fails while parsing overrides in the `_Gtk3.pyi`

`tools/generate.py Gtk 3.0 -o ./src/gi-stubs/repository/_Gtk3.pyi`

fails with

```python
Traceback (most recent call last):
  File "/home/lovetox/projects/pygobject-stubs/tools/generate.py", line 947, in <module>
    overrides = parse.parse(file.read())
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovetox/projects/pygobject-stubs/tools/parse.py", line 170, in parse
    overridden_symbols = _search_overridden_symbols(input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lovetox/projects/pygobject-stubs/tools/parse.py", line 69, in _search_overridden_symbols
    raise ParseError(f"Wrong indentation at line: {i}")
```

Seems it does not expect function definitions on module level having multiple lines

@mat-xc

**Comment by lovetox** [comment]
```
def rc_get_style_by_paths(
    settings: Settings,
    widget_path: Optional[str],
    class_path: Optional[str],
    type: Type,
) -> Optional[Style]: ...
```

the class regex hits on the argument `class_path`
