### ISSUE TITLE
some problems in pygobject installation

### ISSUE THREAD

**Issue by zengchang233** [pygobject/pygobject-stubs#4]
```
Collecting pygobject
  Using cached https://files.pythonhosted.org/packages/8c/1f/76533985b054473ef6ab1ba4d9c00d62da502f8b43d3171ae588ec81ae93/PyGObject-3.30.4.tar.gz
Requirement already satisfied: pycairo>=1.11.1 in ./Application/anaconda3/lib/python3.6/site-packages (from pygobject) (1.18.1)
Building wheels for collected packages: pygobject
  Running setup.py bdist_wheel for pygobject: started
  Running setup.py bdist_wheel for pygobject: finished with status 'error'
  Complete output from command /home/zengchang/Application/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3xwlsq4p/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-4ei2f011 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/pygtkcompat
  copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-3.6/pygtkcompat
  copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-3.6/pygtkcompat
  copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-3.6/pygtkcompat
  creating build/lib.linux-x86_64-3.6/gi
  copying gi/__init__.py -> build/lib.linux-x86_64-3.6/gi
  copying gi/_propertyhelper.py -> build/lib.linux-x86_64-3.6/gi
  copying gi/_option.py -> build/lib.linux-x86_64-3.6/gi
  copying gi/_gtktemplate.py -> build/lib.linux-x86_64-3.6/gi
  copying gi/importer.py -> build/lib.linux-x86_64-3.6/gi
  copying gi/module.py -> build/lib.linux-x86_64-3.6/gi
  copying gi/pygtkcompat.py -> build/lib.linux-x86_64-3.6/gi
  copying gi/_compat.py -> build/lib.linux-x86_64-3.6/gi
  copying gi/_ossighelper.py -> build/lib.linux-x86_64-3.6/gi
  copying gi/_error.py -> build/lib.linux-x86_64-3.6/gi
  copying gi/_signalhelper.py -> build/lib.linux-x86_64-3.6/gi
  copying gi/types.py -> build/lib.linux-x86_64-3.6/gi
  copying gi/docstring.py -> build/lib.linux-x86_64-3.6/gi
  copying gi/_constants.py -> build/lib.linux-x86_64-3.6/gi
  creating build/lib.linux-x86_64-3.6/gi/repository
  copying gi/repository/__init__.py -> build/lib.linux-x86_64-3.6/gi/repository
  creating build/lib.linux-x86_64-3.6/gi/overrides
  copying gi/overrides/__init__.py -> build/lib.linux-x86_64-3.6/gi/overrides
  copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-3.6/gi/overrides
  copying gi/overrides/GObject.py -> build/lib.linux-x86_64-3.6/gi/overrides
  copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-3.6/gi/overrides
  copying gi/overrides/GdkPixbuf.py -> build/lib.linux-x86_64-3.6/gi/overrides
  copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-3.6/gi/overrides
  copying gi/overrides/Gio.py -> build/lib.linux-x86_64-3.6/gi/overrides
  copying gi/overrides/GLib.py -> build/lib.linux-x86_64-3.6/gi/overrides
  copying gi/overrides/Pango.py -> build/lib.linux-x86_64-3.6/gi/overrides
  copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-3.6/gi/overrides
  running build_ext
  pycairo: new API
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 1241, in <module>
      main()
    File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 1236, in main
      zip_safe=False,
    File "/home/zengchang/Application/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/zengchang/Application/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 1076, in run
      self._setup_extensions()
    File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 1071, in _setup_extensions
      add_pycairo(gi_cairo_ext)
    File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 1055, in add_pycairo
      ext.include_dirs += [get_pycairo_include_dir()]
    File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 877, in get_pycairo_include_dir
      include_dir = find_path(find_new_api())
    File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 822, in find_new_api
      import cairo
    File "/home/zengchang/Application/anaconda3/lib/python3.6/site-packages/cairo/__init__.py", line 1, in <module>
      from ._cairo import *  # noqa: F401,F403
  ImportError: /home/zengchang/Application/anaconda3/lib/python3.6/site-packages/cairo/_cairo.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cairo_svg_surface_set_document_unit
  
  ----------------------------------------
  Failed building wheel for pygobject
  Running setup.py clean for pygobject
Failed to build pygobject
Installing collected packages: pygobject
  Running setup.py install for pygobject: started
    Running setup.py install for pygobject: finished with status 'error'
    Complete output from command /home/zengchang/Application/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3xwlsq4p/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-rmd60thi/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/pygtkcompat
    copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-3.6/pygtkcompat
    copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-3.6/pygtkcompat
    copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-3.6/pygtkcompat
    creating build/lib.linux-x86_64-3.6/gi
    copying gi/__init__.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/_propertyhelper.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/_option.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/_gtktemplate.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/importer.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/module.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/pygtkcompat.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/_compat.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/_ossighelper.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/_error.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/_signalhelper.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/types.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/docstring.py -> build/lib.linux-x86_64-3.6/gi
    copying gi/_constants.py -> build/lib.linux-x86_64-3.6/gi
    creating build/lib.linux-x86_64-3.6/gi/repository
    copying gi/repository/__init__.py -> build/lib.linux-x86_64-3.6/gi/repository
    creating build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/__init__.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/GObject.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/GdkPixbuf.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/Gio.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/GLib.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/Pango.py -> build/lib.linux-x86_64-3.6/gi/overrides
    copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-3.6/gi/overrides
    running build_ext
    pycairo: new API
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 1241, in <module>
        main()
      File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 1236, in main
        zip_safe=False,
      File "/home/zengchang/Application/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/zengchang/Application/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/zengchang/Application/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 1076, in run
        self._setup_extensions()
      File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 1071, in _setup_extensions
        add_pycairo(gi_cairo_ext)
      File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 1055, in add_pycairo
        ext.include_dirs += [get_pycairo_include_dir()]
      File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 877, in get_pycairo_include_dir
        include_dir = find_path(find_new_api())
      File "/tmp/pip-install-3xwlsq4p/pygobject/setup.py", line 822, in find_new_api
        import cairo
      File "/home/zengchang/Application/anaconda3/lib/python3.6/site-packages/cairo/__init__.py", line 1, in <module>
        from ._cairo import *  # noqa: F401,F403
    ImportError: /home/zengchang/Application/anaconda3/lib/python3.6/site-packages/cairo/_cairo.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cairo_svg_surface_set_document_unit
    
    ----------------------------------------
Command "/home/zengchang/Application/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3xwlsq4p/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-rmd60thi/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-3xwlsq4p/pygobject/
```

When I use pip install pygobject install the package, I got the error information above. How can I solve it? Do you have any idea?

**Comment by lazka** [comment]
Looks like you somehow installed a pycairo that was build against a newer cairo than you have.

```
pipr3 install --no-binary ":all:" pycairo
```

might help

**Comment by Maria-UET** [comment]
Make sure that you are not using Conda. 

sudo apt update
sudo apt install python3-pip -y

Install these dependencies
sudo apt install libjpeg8-dev zlib1g-dev libtiff-dev libfreetype6 libfreetype6-dev libwebp-dev libopenjp2-7-dev libopenjp2-7-dev -y

Also update pip.
sudo -H pip3 install -U pip

This worked for me.

**Comment by lovetox** [comment]
Closing after 3 years being stale and no further reply from the issue creator

**Comment by SBarkovskiy** [comment]
> Make sure that you are not using Conda.
> 
> `sudo apt update sudo apt install python3-pip -y`
> 
> Install these dependencies `sudo apt install libjpeg8-dev zlib1g-dev libtiff-dev libfreetype6 libfreetype6-dev libwebp-dev libopenjp2-7-dev libopenjp2-7-dev -y`
> 
> Also update pip. `sudo -H pip3 install -U pip`
> 
> This worked for me.

Hey! Thank you!

`sudo apt install libgirepository1.0-dev` helped as well
