### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0

### ISSUE THREAD

**Issue by faridelya** [pygobject/pygobject-stubs#97]
Hi hope you all doing good.

i have install PyGObject but when I run .py module I got this error.

not found any solution.
```
python ds_app.py 
Traceback (most recent call last):
  File "ds_app.py", line 23, in <module>
    from deepstream.utils.common import is_aarch64
  File "/home/experts-vision/Documents/Jetson-app/Jetson_client/deepstream/../deepstream/utils/common.py", line 7, in <module>
    import gi
  File "/home/experts-vision/anaconda3/envs/deep/lib/python3.8/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0

```

**Comment by lovetox** [comment]
This is the wrong project, you probably mean https://gitlab.gnome.org/GNOME/pygobject

though this looks like a packaging problem
